# Generated by Django 3.2.4 on 2021-06-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210610_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doc',
        ),
    ]
